# Generated by Django 5.1.1 on 2024-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='NBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, default='kamalesh', max_length=35)),
                ('pub_date', models.DateField(auto_now=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('readtime', models.IntegerField()),
            ],
        ),
    ]
