# Generated by Django 5.1.1 on 2024-10-08 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_nblogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nblogs',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
